//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using Unity.Services.Multiplay.Apis.GameServer;
using Unity.Services.Wire.Internal;

namespace Unity.Services.Multiplay
{
    /// <summary>
    /// MultiplayService
    /// </summary>
    internal static class MultiplayServiceSdk
    {
        /// <summary>
        /// The static instance of MultiplayService.
        /// </summary>
        public static IMultiplayServiceSdk Instance { get; internal set; }
    }

    /// <summary> Interface for MultiplayService</summary>
    internal interface IMultiplayServiceSdk
    {
        
        /// <summary> Accessor for GameServerApi methods.</summary>
        IGameServerApiClient GameServerApi { get; set; }

        IWireDirect WireDirect { get; set; }

        IServerConfigReader ServerConfigReader { get; set; }

        /// <summary> Configuration properties for the service.</summary>
        Configuration Configuration { get; set; }
    }
}
