//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System.Threading.Tasks;
using System.Collections.Generic;
using Unity.Services.Multiplay.Models;
using Unity.Services.Multiplay.Http;
using Unity.Services.Authentication.Internal;
using Unity.Services.Multiplay.GameServer;

namespace Unity.Services.Multiplay.Apis.GameServer
{
    /// <summary>
    /// Interface for the GameServerApiClient
    /// </summary>
    internal interface IGameServerApiClient
    {
            /// <summary>
            /// Async Operation.
            /// Indicates a server is ready to receive players.
            /// </summary>
            /// <param name="request">Request object for ReadyServer.</param>
            /// <param name="operationConfiguration">Configuration for ReadyServer.</param>
            /// <returns>Task for a Response object containing status code, headers, and JsonObject object.</returns>
            /// <exception cref="Unity.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<JsonObject>> ReadyServerAsync(Unity.Services.Multiplay.GameServer.ReadyServerRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Subscribe to game server lifecycle events.
            /// </summary>
            /// <param name="request">Request object for SubscribeServer.</param>
            /// <param name="operationConfiguration">Configuration for SubscribeServer.</param>
            /// <returns>Task for a Response object containing status code, headers.</returns>
            /// <exception cref="Unity.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response> SubscribeServerAsync(Unity.Services.Multiplay.GameServer.SubscribeServerRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Indicates a server is not ready to receive allocations.
            /// </summary>
            /// <param name="request">Request object for UnreadyServer.</param>
            /// <param name="operationConfiguration">Configuration for UnreadyServer.</param>
            /// <returns>Task for a Response object containing status code, headers, and JsonObject object.</returns>
            /// <exception cref="Unity.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<JsonObject>> UnreadyServerAsync(Unity.Services.Multiplay.GameServer.UnreadyServerRequest request, Configuration operationConfiguration = null);

    }

    ///<inheritdoc cref="IGameServerApiClient"/>
    internal class GameServerApiClient : BaseApiClient, IGameServerApiClient
    {
        private IAccessToken _accessToken;
        private const int _baseTimeout = 10;
        private Configuration _configuration;
        /// <summary>
        /// Accessor for the client configuration object. This returns a merge
        /// between the current configuration and the global configuration to
        /// ensure the correct combination of headers and a base path (if it is
        /// set) are returned.
        /// </summary>
        public Configuration Configuration
        {
            get {
                // We return a merge between the current configuration and the
                // global configuration to ensure we have the correct
                // combination of headers and a base path (if it is set).
                Configuration globalConfiguration = new Configuration("http://127.0.0.1:8086", 10, 4, null);
                if (MultiplayServiceSdk.Instance != null)
                {
                    globalConfiguration = MultiplayServiceSdk.Instance.Configuration;
                }
                return Configuration.MergeConfigurations(_configuration, globalConfiguration);
            }
        }

        /// <summary>
        /// GameServerApiClient Constructor.
        /// </summary>
        /// <param name="httpClient">The HttpClient for GameServerApiClient.</param>
        /// <param name="accessToken">The Authentication token for the client.</param>
        /// <param name="configuration"> GameServerApiClient Configuration object.</param>
        public GameServerApiClient(IHttpClient httpClient,
            IAccessToken accessToken,
            Configuration configuration = null) : base(httpClient)
        {
            // We don't need to worry about the configuration being null at
            // this stage, we will check this in the accessor.
            _configuration = configuration;

            _accessToken = accessToken;
        }


        /// <summary>
        /// Async Operation.
        /// Indicates a server is ready to receive players.
        /// </summary>
        /// <param name="request">Request object for ReadyServer.</param>
        /// <param name="operationConfiguration">Configuration for ReadyServer.</param>
        /// <returns>Task for a Response object containing status code, headers, and JsonObject object.</returns>
        /// <exception cref="Unity.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<JsonObject>> ReadyServerAsync(Unity.Services.Multiplay.GameServer.ReadyServerRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(JsonObject)   },{"404", typeof(Models.ErrorResponseBody)   },{"500", typeof(Models.ErrorResponseBody)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("POST",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<JsonObject>(response, statusCodeToTypeMap);
            return new Response<JsonObject>(response, handledResponse);
        }


        /// <summary>
        /// Async Operation.
        /// Subscribe to game server lifecycle events.
        /// </summary>
        /// <param name="request">Request object for SubscribeServer.</param>
        /// <param name="operationConfiguration">Configuration for SubscribeServer.</param>
        /// <returns>Task for a Response object containing status code, headers.</returns>
        /// <exception cref="Unity.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response> SubscribeServerAsync(Unity.Services.Multiplay.GameServer.SubscribeServerRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"101",  null },{"400", typeof(ErrorResponseBody)   },{"404", typeof(ErrorResponseBody)   },{"500", typeof(ErrorResponseBody)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("GET",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            ResponseHandler.HandleAsyncResponse(response, statusCodeToTypeMap);
            return new Response(response);
        }


        /// <summary>
        /// Async Operation.
        /// Indicates a server is not ready to receive allocations.
        /// </summary>
        /// <param name="request">Request object for UnreadyServer.</param>
        /// <param name="operationConfiguration">Configuration for UnreadyServer.</param>
        /// <returns>Task for a Response object containing status code, headers, and JsonObject object.</returns>
        /// <exception cref="Unity.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<JsonObject>> UnreadyServerAsync(Unity.Services.Multiplay.GameServer.UnreadyServerRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(JsonObject)   },{"404", typeof(Models.ErrorResponseBody)   },{"500", typeof(Models.ErrorResponseBody)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("POST",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<JsonObject>(response, statusCodeToTypeMap);
            return new Response<JsonObject>(response, handledResponse);
        }

    }
}
