//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System.Threading.Tasks;
using System.Collections.Generic;
using Unity.Services.Multiplay.Models;
using Unity.Services.Multiplay.Http;
using Unity.Services.Authentication.Internal;
using Unity.Services.Multiplay.Payload;
using System.Text;

namespace Unity.Services.Multiplay.Apis.Payload
{
    /// <summary>
    /// Interface for the PayloadApiClient
    /// </summary>
    internal interface IPayloadApiClient
    {
            /// <summary>
            /// Async Operation.
            /// Retrieve an allocation&#39;s payload.
            /// </summary>
            /// <param name="request">Request object for PayloadAllocation.</param>
            /// <param name="operationConfiguration">Configuration for PayloadAllocation.</param>
            /// <returns>Task for a Response object containing status code, headers, and string object.</returns>
            /// <exception cref="Unity.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<string>> PayloadAllocationAsync(Unity.Services.Multiplay.Payload.PayloadAllocationRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Retrieve a JWT token for payloads.
            /// </summary>
            /// <param name="request">Request object for PayloadToken.</param>
            /// <param name="operationConfiguration">Configuration for PayloadToken.</param>
            /// <returns>Task for a Response object containing status code, headers, and Models.PayloadTokenResponseBody object.</returns>
            /// <exception cref="Unity.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<Models.PayloadTokenResponseBody>> PayloadTokenAsync(Unity.Services.Multiplay.Payload.PayloadTokenRequest request, Configuration operationConfiguration = null);

    }

    ///<inheritdoc cref="IPayloadApiClient"/>
    internal class PayloadApiClient : BaseApiClient, IPayloadApiClient
    {
        private IAccessToken _accessToken;
        private const int _baseTimeout = 10;
        private Configuration _configuration;
        /// <summary>
        /// Accessor for the client configuration object. This returns a merge
        /// between the current configuration and the global configuration to
        /// ensure the correct combination of headers and a base path (if it is
        /// set) are returned.
        /// </summary>
        public Configuration Configuration
        {
            get {
                // We return a merge between the current configuration and the
                // global configuration to ensure we have the correct
                // combination of headers and a base path (if it is set).
                Configuration globalConfiguration = new Configuration("http://127.0.0.1:8086", 10, 4, null);
                if (MultiplayServiceSdk.Instance != null)
                {
                    globalConfiguration = MultiplayServiceSdk.Instance.Configuration;
                }
                return Configuration.MergeConfigurations(_configuration, globalConfiguration);
            }
            set { _configuration = value; }
        }

        /// <summary>
        /// PayloadApiClient Constructor.
        /// </summary>
        /// <param name="httpClient">The HttpClient for PayloadApiClient.</param>
        /// <param name="accessToken">The Authentication token for the client.</param>
        /// <param name="configuration"> PayloadApiClient Configuration object.</param>
        public PayloadApiClient(IHttpClient httpClient,
            IAccessToken accessToken,
            Configuration configuration = null) : base(httpClient)
        {
            // We don't need to worry about the configuration being null at
            // this stage, we will check this in the accessor.
            _configuration = configuration;

            _accessToken = accessToken;
        }


        /// <summary>
        /// Async Operation.
        /// Retrieve an allocation&#39;s payload.
        /// </summary>
        /// <param name="request">Request object for PayloadAllocation.</param>
        /// <param name="operationConfiguration">Configuration for PayloadAllocation.</param>
        /// <returns>Task for a Response object containing status code, headers, and string object.</returns>
        /// <exception cref="Unity.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<string>> PayloadAllocationAsync(Unity.Services.Multiplay.Payload.PayloadAllocationRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(string)   },{"400", typeof(Models.PayloadAllocationErrorResponseBody)   },{"500", typeof(Models.PayloadAllocationErrorResponseBody)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("GET",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            ResponseHandler.HandleAsyncResponse(response, statusCodeToTypeMap);
            var handledResponse = Encoding.UTF8.GetString(response.Data);
            return new Response<string>(response, handledResponse);
        }


        /// <summary>
        /// Async Operation.
        /// Retrieve a JWT token for payloads.
        /// </summary>
        /// <param name="request">Request object for PayloadToken.</param>
        /// <param name="operationConfiguration">Configuration for PayloadToken.</param>
        /// <returns>Task for a Response object containing status code, headers, and Models.PayloadTokenResponseBody object.</returns>
        /// <exception cref="Unity.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<Models.PayloadTokenResponseBody>> PayloadTokenAsync(Unity.Services.Multiplay.Payload.PayloadTokenRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(Models.PayloadTokenResponseBody)   },{"500", typeof(Models.PayloadTokenResponseBody)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("GET",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<Models.PayloadTokenResponseBody>(response, statusCodeToTypeMap);
            return new Response<Models.PayloadTokenResponseBody>(response, handledResponse);
        }

    }
}
