//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Multiplay.Http;



namespace Unity.Services.Multiplay.Models
{
    /// <summary>
    /// KeyValuePair model
    /// </summary>
    [Preserve]
    [DataContract(Name = "KeyValuePair")]
    public class KeyValuePair
    {
        /// <summary>
        /// Creates an instance of KeyValuePair.
        /// </summary>
        /// <param name="key">key param</param>
        /// <param name="value">value param</param>
        [Preserve]
        public KeyValuePair(string key, string value)
        {
            Key = key;
            Value = value;
        }

        /// <summary>
        /// 
        /// </summary>
        [Preserve]
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = true)]
        public string Key{ get; }
        /// <summary>
        /// 
        /// </summary>
        [Preserve]
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public string Value{ get; }
    
    }
}

